source 'https://rubygems.org'
ruby '2.3.4'

gem 'twilio-ruby'

gem 'sprockets', '>= 3.0.0'
gem 'sprockets-es6'
gem 'omniauth-google-oauth2'

gem 'cloudinary', '1.1.7'
gem 'attachinary', github: 'assembler/attachinary'
gem 'jquery-fileupload-rails'
gem 'omniauth-facebook'
gem 'devise'
gem 'figaro'
gem 'coffee-rails'
gem 'jbuilder', '~> 2.0'
gem 'pg'
gem 'puma'
gem 'rails', '5.0.5'
gem 'redis', '< 4.0.0'

gem 'autoprefixer-rails'
gem 'coffee-rails'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'jquery-rails'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'
gem 'pundit'
gem 'momentjs-rails', '>= 2.9.0'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.47'
gem 'money-rails'
gem 'stripe'
gem 'pundit'
gem 'faker'
gem 'postmark-rails'
gem 'webpush'

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem "letter_opener"
end
